### ISSUE TITLE
Errore con data di uscita incerta

### ISSUE THREAD

**Issue by leandromacrini** [MainKronos/AnimeWorld-API#10]
Quando la data di uscita riportata su animeworld è qualcosa tipo '?? Ottobre 2023' viene generato un errore di parsing non gestito:

File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '?? Ottobre 2023' does not match format '%d %B %Y'

**Comment by MainKronos** [comment]
Hai ragione, non avevo pensato a questo caso. Grazie per la segnalazione 👍.
Lo correggerò quanto prima.

**Comment by MainKronos** [comment]
Corretto con la nuova versione [`1.6.2`](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.6.2)
