### ISSUE TITLE
Documentazione in inglese

### ISSUE THREAD

**Issue by NotSoMik** [MainKronos/AnimeWorld-API#14]
Ciao, vorrei suggerire qualcosa più che segnalare un problema. Sto lavorando a un sito di streaming anime con sviluppatori inglesi, e sarebbe utile tradurre la documentazione in inglese. Attualmente il nostro sito supporta solo l'inglese, ma pensiamo di renderlo multilingua in futuro, includendo l'italiano. Tuttavia, in un team di sviluppatori stranieri dove solo io parlo italiano, risulta difficile utilizzare la documentazione attuale. Se decideste di tradurla in inglese, sarei disponibile ad offrire il mio aiuto per semplificarne la gestione.

**Comment by MainKronos** [comment]
Hai ragione. Non ho fatto una documentazione in inglese perchè non la reputavo necessaria, però non avevo considerato il caso di un integrazione con un sito internazionale. 
Provvedo ad aggiungere la traduzione in inglese

**Comment by NotSoMik** [comment]
Perfetto, gentilissimo 👋🏻

**Comment by MainKronos** [comment]
Ho riscritto la maggior parte della documentazione, tranne [API Reference](https://mainkronos.github.io/AnimeWorld-API/api-reference/developer-interface/) perchè tutta la descrizione è inserita direttamente nel codice (lo farò prossimamente)

Ho tradotto con "l'accetta", ma dovrebbe essere tutto abbastanza leggibile. Se trovi qualche frase che non ha senso apri una Pull con le modifiche o scrivi qui sotto.

**Comment by NotSoMik** [comment]
Certamente, ti farò sapere, grazie.

**Comment by NotSoMik** [comment]
A me sembra tutto apposto, l'unica cosa sarebbe interessante aggiungere un: "nextAiringEpisode" così da poter fare una cosa simile
![Screenshot_20231204_070952_Discord](https://github.com/MainKronos/AnimeWorld-API/assets/74645196/2015b9a5-7473-4ac7-b3ac-93536b1eb49f)

**Comment by MainKronos** [comment]
C'è modo di riuscire a reperire questa informazione dal sito di animeworld?

**Comment by NotSoMik** [comment]
non so, non seguo molto anime world, pensavo avesse questa caratteristica

**Comment by GioGio03** [comment]
Se non sbanglio nella libreria questa feature non sta, quindi potete mettere una sorta di filterby
![Screenshot_20231207_075218_Opera](https://github.com/MainKronos/AnimeWorld-API/assets/84544068/37afff7e-ee20-46cf-a273-ecc0f3f0619b)
 cosa da poter filtrare gli anime in base al genere, stato, anno ecc.

**Comment by GioGio03** [comment]
> C'è modo di riuscire a reperire questa informazione dal sito di animeworld?

Comunque si animeworld ha [questa cosa](https://www.animeworld.so/play/one-piece-subita.qzG-LE/CnO83E
![Uploading Screenshot_20231207_075851_Opera.jpg…]()
)

**Comment by MainKronos** [comment]
[questa cosa](https://www.animeworld.so/play/one-piece-subita.qzG-LE/CnO83E), cosa in particolare? 😅
Vedo solo la pagina di One Piece

**Comment by NotSoMik** [comment]
![Screenshot_20231208_110912_Samsung Internet](https://github.com/MainKronos/AnimeWorld-API/assets/74645196/819996c3-098f-4a57-b3a8-4d10417b714a)

**Comment by GioGio03** [comment]
> ![Screenshot_20231208_110912_Samsung Internet](https://private-user-images.githubusercontent.com/74645196/289036336-819996c3-098f-4a57-b3a8-4d10417b714a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjM5ODcsIm5iZiI6MTcwMjMyMzY4NywicGF0aCI6Ii83NDY0NTE5Ni8yODkwMzYzMzYtODE5OTk2YzMtMDk4Zi00YTU3LWIzYTgtNGQxMDQxN2I3MTRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE5NDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NWExOGMwMTZkNzJiMTA5MDFmMGZlZjY2YzE3OWMyMmJhZjcwNzA4YjRlMjk5NDg1ZGM3ZDg0Y2NlZjRiYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I58USlH2rrYd5SDCW3OseAaBgbQvjigVdUbWQxrWnxk)

Esatto

**Comment by GioGio03** [comment]
> Se non sbanglio nella libreria questa feature non sta, quindi potete mettere una sorta di filterby ![Screenshot_20231207_075218_Opera](https://private-user-images.githubusercontent.com/84544068/288662246-37afff7e-ee20-46cf-a273-ecc0f3f0619b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTk3NzYsIm5iZiI6MTcwMjM5OTQ3NiwicGF0aCI6Ii84NDU0NDA2OC8yODg2NjIyNDYtMzdhZmZmN2UtZWUyMC00NmNmLWEyNzMtZWNjMGYzZjA2MTliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NTBmNzEyODFhOTc4NTdkNzZmNTUyMTlkNjQ2Y2EzMGNkMzExYTQ1OWNkYTZjNGQ5ZGRiMGQ3ZTdiZTEzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fj3nUe6PpfH56z8-pd2VwNyl34ri2KTZd_RFIQZL6Ps) cosa da poter filtrare gli anime in base al genere, stato, anno ecc.

^^
